paths:
  /store/create:
    post:
      tags:
        - Store
      summary: 가게생성
      parameters:
      - name: createStore
        in: body
        required: true
        schema:
          properties:
            name:
              type: string
              description: 가게 이름
              example: swagger Test Store Name
            address:
              type: string
              description: 가게 주소
              example: swagger Test Store Address
            region_id:
              type: number
              description: 가게가 속한 지역 번호
              example: 1
      responses:
        '200':
          description: 가게 생성 성공!
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              data:
                type: object
                example: {
                  "name": "swagger Test Store Name",
                  "address": "swagger Test Store Address",
                  "region_id": 1
                }
                
        '400':
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.
  /store/review/1:
    post:
      tags:
        - Review
      summary: 가게에 리뷰 작성
      parameters:
      - name: writeReview
        in: body
        required: true
        schema:
          properties:
            member_id:
              type: number
              description: 작성하는 멤버의 id
              example: 1
            store_id:
              type: number
              description: 작성할 가게의 id
              example: 1
            score:
              type: number
              description: 리뷰 점수
              example: 5d
            content:
              type: string
              description: 리뷰 내용
              example: swagger Store Review Test Content
      responses:
        '200':
          description: 리뷰 생성 성공!
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              data:
                type: object
                example: {
                  "member_id": 1,
                  "user_id": 1,
                  "score": 5,
                  "content": "swagger Test Store Reivew Test Content",
                }
                
        '400':
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.